### ISSUE TITLE
Prefixes Re-Announcement Monitoring.

### ISSUE THREAD

**Issue by deepuad** [nttgin/BGPalerter#428] opened 2020-12-11 13:02 UTC
**Describe what you would like to achieve**
To enable Prefixes Re-Announcement monitoring.

**Describe why the current solution (if any) is not satisfactory**
Couldn't find the Re-Announcement monitor in the config.yml file

**Provide an example**
Provide an example in terms of prefixes and BGP messages. Possibly provide a snippet of config.yml and prefixes.yml.
The prefix 2406:7400:d::/48 (No description provided (valid ROA available)) has been withdrawn. It is no longer visible from 20 peers
![image](https://user-images.githubusercontent.com/65802763/101906583-2df97100-3bdf-11eb-863f-f6e10ea392b4.png)
![image](https://user-images.githubusercontent.com/65802763/101906484-086c6780-3bdf-11eb-9ab1-d1754f0eef0f.png)

**Your information**
Dileep AS:24309

**Comment by massimocandela** [comment] 2020-12-13 20:43
Hi @deepuad,

With re-announcement, you mean when a prefix "no longer visible" comes back to be visible? or you mean multiple announcements?

**Comment by deepuad** [comment] 2020-12-14 03:57
Hi @massimocandela,

Yes, Sir, I'm asking if a "no longer visible" prefix comes back?

**Comment by massimocandela** [comment] 2020-12-14 13:45
Thanks for the explanation. I'm closing this since it's a duplicate of #60

**Closed by massimocandela** 2020-12-14 13:45 UTC
Labels: enhancement

**Comment by pistonov** [comment] 2022-06-21 14:53
I made a simple bash script to notify about restored prefixes [BGPalerter_recovery_notify](https://github.com/pistonov/BGPalerter_recovery_notify)
