### ISSUE TITLE
Upgrade notification still happening after upgrade

### ISSUE THREAD

**Issue by V3XATI0N** [nttgin/BGPalerter#1052] opened 2023-03-08 17:29 UTC
**Describe the bug**
We updated from 1.31.1 to 1.32.0, but our notifications are still telling us to upgrade. This is running in EKS, and I've verified from the running pod that it is in fact version 1.32.0 that starts up, but it's still telling us to upgrade from 1.31.1.

**Comment by massimocandela** [comment] 2023-03-08 18:09
Hi @V3XATI0N,

I cannot reproduce this. I did not experience this on any of my vms and running the code I checked that the module is able to correctly identify that the version running doesn't require update.

Are you running the binary?

**Comment by V3XATI0N** [comment] 2023-03-08 18:11
thanks, yeah we are just running the published docker image nttgin/bgpalerter:v1.32.0 , and when I run the same container locally or log in via kubectl it says it's the right version. it may be that we have a ghost container still running somewhere, so maybe this bug doesn't belong here

**Comment by massimocandela** [comment] 2023-03-08 19:42
I'm going to close this then. If you find something let me know.

**Closed by massimocandela** 2023-03-08 19:42 UTC
Labels: bug
