### ISSUE TITLE
Send 1 alert when a prefix is announced after been witthdrawn.

### ISSUE THREAD

**Issue by aalmenar** [nttgin/BGPalerter#229] opened 2020-05-02 16:11 UTC
Today, when a prefix is withdrawn you get an alert, it could be fine to get 1 alert when prefix is online again.

**Comment by massimocandela** [comment] 2020-05-02 16:23
Hi Adrian,

This is duplicate of https://github.com/nttgin/BGPalerter/issues/60
So I will close this and move the discussion in the other topic.

Quick answer: yes, it is in the pipeline but it requires a minimum of changes to persist a state

**Closed by massimocandela** 2020-05-02 16:23 UTC
Labels: enhancement

**Comment by rajeev7086** [comment] 2020-11-01 17:57
+1 , still there is no work around on getting notification that prefix is online again , nether it is not getting noisy msg till it is not online , after changing notification seconds to 60 still not getting renotification . 
this is very much required to get the nighty msg of withdrawal prefix got fixed by online again .
