### ISSUE TITLE
Possible memory leak when monitoring large number of prefixes

### ISSUE THREAD

**Issue by mirceaulinic** [nttgin/BGPalerter#114] opened 2019-12-20 14:24 UTC
Hello,

Before anything, thanks for this project. I've been watching it for a while, and now finally deployed it... I hope I'll be able to contribute to at some point, for now, at least, with some reports.

**Describe the bug**

Well, it is not exactly a bug (or maybe it is), but I've noticed the memory is steadily increasing. In 24 hours after deploying the app, the memory footprint grew from 150MB to over 800MB, and it looks like it's only going to be getting worse - see screenshot below:

![BGPalerter Mem Usage Grafana](https://user-images.githubusercontent.com/16694679/71260911-f3def180-2333-11ea-8da1-be629f0d5743.png)

The CPU usage seems pretty stable however.

I'm yet to play with Node Js, but in general a pattern like that means there's a possibility of a memory leak somewhere.

**Provide an example**
Provide an example in terms of prefixes and BGP messages. Possibly provide a snippet of config.yml and prefixes.yml.

Nothing really specific, pretty much all the prefixes from https://bgp.he.net/AS14061#_prefixes and https://bgp.he.net/AS14061#_prefixes6, e.g.,

```yaml
"5.101.96.0/21":
  description: "Some description"
  asn: 14061
  ignoreMorespecifics: false
  ignore: false
```

3581 prefixes in total.

**Expected behavior**

Given the high number of prefixes, I'd expect to see a pretty important memory footprint, but I find an always growing figure more worrying because it's not easily predictable how much resources you're going to need on the long term.

**Are you using the binary or the source code?**

A custom Docker image based on [nttgin/BGPalerter](https://hub.docker.com/r/nttgin/bgpalerter), so source code.

**Your information**
Provide your name and your AS/company (see Bert Hubert's post https://berthub.eu/articles/posts/anonymous-help/).

AS14061, DigitalOcean.

Cheers!

**Comment by massimocandela** [comment] 2019-12-20 18:21
Hello Mircea, 

Thanks for the report!
I am really interested in understanding this so I will ask you more questions. I hope you can assist me because I am (both privately and as NTT) monitoring a greater amount of prefixes but I cannot see the same memory pattern.

* Could you please post here your config.yml? I would like to check what monitors and reporting you have in place (be careful to don't post passwords or webhooks contained in the configuration).
Also, high values for notificationIntervalSeconds increases the memory footprint during such interval. A alertOnlyOnce set to true is known to create a memory leak (described also in the config). The reason is described [here](https://github.com/nttgin/BGPalerter/issues/25).

* Are you monitoring something that generates a lot of BGP updates (not necessarily alerts)?

* Could you please let it run longer and let me know if the memory consumption stabilise after some time?

* Is there any warning/error in logs/error-*.log?

Thanks

**Comment by mirceaulinic** [comment] 2019-12-23 10:10
Hi @massimocandela,

Thanks for looking into this. Yes, it's quite possible there's a misconfiguration on my side. Please find below the details.

> - Could you please post here your config.yml? 

It's simply https://github.com/nttgin/BGPalerter/blob/master/config.yml.example, with the only difference that the `reportSlack` section under `reports` is uncommented (and provided with the webhook URL).

Perhaps it also worth mentioning that in `prefixes.yaml`, besides the configuration I've mentioned, I also have:

```yaml
options:
  monitorASns:
    14061:
      group: default
```

> Are you monitoring something that generates a lot of BGP updates (not necessarily alerts)?

Normally, no.

> - Could you please let it run longer and let me know if the memory consumption stabilise after some time?

I let it run over the weekend, but due to memory limits (2GB), the application has been restarted (two times within 72h) - so it continues to grow linearly till 2BG at least. I can increase the limits if you'd like me to keep watching beyond 2GB.

![BGPalerter Mem Usage Grafana 72h](https://user-images.githubusercontent.com/16694679/71349963-1c4f3180-2568-11ea-8404-f5b5ce197547.png)

> - Is there any warning/error in logs/error-*.log?

Yes, quite a few:

```
/opt/bgpalerter/logs # cat error-2019-12-21.log
2019-12-21T11:47:56.885Z [production] info: ris connector connected
2019-12-21T11:55:20.530Z [production] error: Error: Client network socket disconnected before secure TLS connection was established
2019-12-21T12:20:20.095Z [production] error: 1006
2019-12-21T12:20:25.567Z [production] info: ris connector connected
2019-12-21T14:04:01.480Z [production] error: Error: Client network socket disconnected before secure TLS connection was established
2019-12-21T16:01:37.115Z [production] error: Error: Client network socket disconnected before secure TLS connection was established
2019-12-21T18:03:11.869Z [production] error: Error: Client network socket disconnected before secure TLS connection was established
2019-12-21T19:00:30.542Z [production] error: 1006
2019-12-21T19:00:36.049Z [production] info: ris connector connected
2019-12-21T20:31:13.935Z [production] error: Error: Client network socket disconnected before secure TLS connection was established
2019-12-21T21:24:53.946Z [production] error: 1006
2019-12-21T21:24:59.385Z [production] info: ris connector connected
2019-12-21T22:04:46.337Z [production] error: Error: Client network socket disconnected before secure TLS connection was established
/opt/bgpalerter/logs #
/opt/bgpalerter/logs # cat reports-2019-12-21.log
2019-12-21T11:53:01.282Z [production] verbose: AS14061 is announcing 2400:6180::/48 but this prefix is not in the configured list of announced prefixes
2019-12-21T13:58:07.011Z [production] verbose: AS14061 is announcing some prefixes which are not in the configured list of announced prefixes: 2400:6180::/48,2a03:b0c0::/48,2a03:b0c0:1::/48,2a03:b0c0:2::/48,2a03:b0c0:3::/48,46.101.128.0/17,46.101.96.0/19,139.59.128.0/19,37.139.0.0/19,146.185.160.0/20,146.185.128.0/19,192.81.220.0/22,146.185.176.0/21,82.196.0.0/20,185.14.184.0/22,198.211.120.0/21,198.211.118.0/23,198.199.124.0/22,95.85.0.0/18,188.226.128.0/17
2019-12-21T15:58:16.476Z [production] verbose: AS14061 is announcing some prefixes which are not in the configured list of announced prefixes: 2400:6180::/48,2a03:b0c0::/48,2a03:b0c0:1::/48,2a03:b0c0:2::/48,2a03:b0c0:3::/48,46.101.128.0/17,46.101.96.0/19,139.59.128.0/19,2604:a880::/48,2604:a880:1::/48,2604:a880:2::/48,2604:a880:400::/48,2604:a880:800::/48,2604:a880:801::/48,2604:a880:cad::/48,37.139.0.0/19,146.185.160.0/20,146.185.128.0/19,192.81.220.0/22,146.185.176.0/21,82.196.0.0/20,185.14.184.0/22,198.211.120.0/21,198.211.118.0/23,198.199.124.0/22,95.85.0.0/18,188.226.128.0/17
2019-12-21T18:00:00.393Z [production] verbose: AS14061 is announcing some prefixes which are not in the configured list of announced prefixes: 2400:6180::/48,2a03:b0c0::/48,2a03:b0c0:1::/48,2a03:b0c0:2::/48,2a03:b0c0:3::/48,46.101.128.0/17,46.101.96.0/19,139.59.128.0/19,2604:a880::/48,2604:a880:1::/48,2604:a880:2::/48,2604:a880:400::/48,2604:a880:800::/48,2604:a880:801::/48,2604:a880:cad::/48,37.139.0.0/19,146.185.160.0/20,146.185.128.0/19,192.81.220.0/22,146.185.176.0/21,82.196.0.0/20,185.14.184.0/22,198.211.120.0/21,198.211.118.0/23,198.199.124.0/22,95.85.0.0/18,188.226.128.0/17
2019-12-21T20:11:04.472Z [production] verbose: AS14061 is announcing some prefixes which are not in the configured list of announced prefixes: 2400:6180::/48,2a03:b0c0::/48,2a03:b0c0:1::/48,2a03:b0c0:2::/48,2a03:b0c0:3::/48,46.101.128.0/17,46.101.96.0/19,139.59.128.0/19,2604:a880::/48,2604:a880:1::/48,2604:a880:2::/48,2604:a880:400::/48,2604:a880:800::/48,2604:a880:801::/48,2604:a880:cad::/48,37.139.0.0/19,146.185.160.0/20,146.185.128.0/19,192.81.220.0/22,146.185.176.0/21,82.196.0.0/20,185.14.184.0/22,198.211.120.0/21,198.211.118.0/23,198.199.124.0/22,95.85.0.0/18,188.226.128.0/17,69.55.58.0/23,69.55.52.0/24
2019-12-21T22:02:34.660Z [production] verbose: AS14061 is announcing some prefixes which are not in the configured list of announced prefixes: 2400:6180::/48,2a03:b0c0::/48,2a03:b0c0:1::/48,2a03:b0c0:2::/48,2a03:b0c0:3::/48,46.101.128.0/17,46.101.96.0/19,139.59.128.0/19,2604:a880::/48,2604:a880:1::/48,2604:a880:2::/48,2604:a880:400::/48,2604:a880:800::/48,2604:a880:801::/48,2604:a880:cad::/48,37.139.0.0/19,146.185.160.0/20,146.185.128.0/19,192.81.220.0/22,146.185.176.0/21,82.196.0.0/20,185.14.184.0/22,198.211.120.0/21,198.211.118.0/23,198.199.124.0/22,95.85.0.0/18,188.226.128.0/17,103.253.144.0/22,69.55.58.0/23,69.55.52.0/24
/opt/bgpalerter/logs # 
```

Looking at those logs, my first reaction would be to add the prefixes it is complaining about that are not configured in the list of prefixes. I'm going to add them and see if there's any improvement.

**Comment by massimocandela** [comment] 2019-12-30 15:59
Fyi, I'm still working/investigating on this (in the meanwhile, happy new year).

**Comment by mirceaulinic** [comment] 2020-01-02 13:49
Thanks @massimocandela, and happy new year!

In the meanwhile I have changed the configuration of the prefixes.yml file to start monitoring aggregates (yup, we do announce both aggregates and more specifics altogether :roll_eyes:), however I'm seeing the same pattern:

![BGP Alerter mem aggregates and all](https://user-images.githubusercontent.com/16694679/71669687-7076c480-2d65-11ea-8d9e-a829eb5898d7.png)

Naturally, as we now monitor the aggregates as well, I'm seeing info logs such as:

```
2020-01-01T06:42:37.263Z [production] verbose: Possible change of configuration. A new prefix 2400:6180::/48 is announced by AS14061. It is a more specific of 2400:6180::/32 (APNIC).
2020-01-01T07:02:13.684Z [production] verbose: Possible change of configuration. A new prefix 198.199.124.0/22 is announced by AS14061. It is a more specific of 198.199.64.0/18 (ARIN).
2020-01-01T07:02:13.686Z [production] verbose: Possible change of configuration. A new prefix 146.185.176.0/21 is announced by AS14061. It is a more specific of 146.185.160.0/19 (RIPE).
```

I did so to eliminate a possible cause, although I incline to believe this might be rather related to this error:

```
2020-01-02T12:27:48.334Z [production] error: Error: Client network socket disconnected before secure TLS connection was established
2020-01-02T13:22:14.418Z [production] error: Error: Client network socket disconnected before secure TLS connection was established
2020-01-02T13:27:44.249Z [production] error: Error: Client network socket disconnected before secure TLS connection was established
2020-01-02T11:39:58.606Z [production] error: 1006
```

In 24 hours, there were over 400 occurrences:

```
/opt/bgpalerter/logs # zcat error-2020-01-01.log.gz | grep "Client network socket disconnected" | wc -l
411
```

Any idea what could be the cause of this?

**Comment by massimocandela** [comment] 2020-01-12 13:30
Hi @mirceaulinic,

BGPalerter is in many cases able to automatically optimise the monitoring of aggregates instead of more specifics. That doesn't impact the memory usage.

Anyway, I believe I managed to identify and solve the memory leak in your case. It refers to a specific case, which I don't think impacted anybody else before.

**Please, can you run the latest version of BGPalerter available in `dev` and let me know if this solves the memory leak as soon as possible?** 
You should see a memory usage between ~25Mb and ~200Mb

The error "Client network socket disconnected before secure TLS connection was established" I don't know what is related to. Never seen it before. Could you please try to debug it in your configuration? In case open another ticket with instructions on how to replicate it.

**Comment by mirceaulinic** [comment] 2020-01-14 14:19
Hi Massimo,

Fantastic, thanks a lot (and sorry!) for this amount of work. BTW: I looked over the PR, I'm _almost_ following, but I'd greatly appreciate if you'd take a minute to explain me what's the issue you identified, and it's particular to my use case?

Yes, I have deployed the app with the new basecode, let's see how it goes.

Regarding the "Client network socket disconnected before secure TLS connection was established" error: BGPalerter is deployed behind a firewall that normally drops the connection after 20 minutes. Was thinking it may be related to that. :thinking: Anyway, what's the method you'd recommend to enable the detailed logging of full traces? Thanks!

**Comment by massimocandela** [comment] 2020-01-15 14:16
Yes, I will write you a detailed answer soon. Unfortunately I believe the patch I released in dev for this issue introduced another bug I'm trying to address. So don't invest time in testing it yet.

**Comment by massimocandela** [comment] 2020-01-17 02:04
Ok!! We are there! Please, run the latest code in `dev` for some hours and let me know if you see the memory pattern!

**Comment by mirceaulinic** [comment] 2020-01-18 19:15
A quick update here: as one can notice in the following graph, the memory footprint has been dramatically reduced over the last 24 hours:

![Screenshot_2020-01-18  eng-delivery  docc applications - Grafana](https://user-images.githubusercontent.com/16694679/72669087-ad111400-3a25-11ea-926d-ab86d77d39e1.png)

If the previous one is not obvious enough, the following may probably give a better image (over the last 2 days, the yellow dashed line represents the moment when I redeployed with the latest code from `dev`) :smiley: 

![Screenshot_2020-01-18  eng-delivery  docc applications - Grafana 2 days](https://user-images.githubusercontent.com/16694679/72669178-b64eb080-3a26-11ea-95f3-e5b9670c63cd.png)

Similarly for the CPU:

![Screenshot_2020-01-18  eng-delivery  docc applications - Grafana cpu](https://user-images.githubusercontent.com/16694679/72669183-bd75be80-3a26-11ea-9ff8-d6e6d9c73c13.png)

Thanks a lot @massimocandela, much appreciated!

**Comment by massimocandela** [comment] 2020-01-18 19:56
In the end this issue you opened gave me the start for a complete profiling and tuning of the code (in addition to fixing the memory leak) in order to reduce memory and cpu usage.
**So glad to see those graphs, you made my day! :D**

The memory leak was triggered by identical BGP messages. In your case many of the prefixes announced by DigitalOcean (e.g. the one of `npm run generate-prefixes -- --a 14061 --o prefixes.yml`) are constantly re-announced (not sure why, maybe you should investigate if that is normal). If you insert a console.log in the code you can see thousands of re-announcement per minute which create CPU spikes.

When this happens, multiple alerts with the same ID are generated. The first of this alert was considered "new" and so it was reported, the others were squashed to generate statistics (e.g. "first seen" and "last seen"). I introduced a bug where the squash was actually retaining the BGP messages. These were anyway going to get garbage collected after `notificationIntervalSeconds` so in a normal situation nobody would have noticed it (just few KB more), but in your case they pile up soon.

Thanks again for reporting.

**Closed** 2020-01-18 20:00 UTC
Labels: bug, next release

**Comment by mirceaulinic** [comment] 2020-01-21 12:56
Hi @massimocandela, 

Just another update here: still working perfectly fine with `dev`. :smile: 

As suggested, I've added some console.log in the code:

```patch
diff --git a/src/consumer.js b/src/consumer.js
index f025bcd..cda140d 100644
--- a/src/consumer.js
+++ b/src/consumer.js
@@ -61,6 +61,10 @@ export default class Consumer {
                 const connector = data.connector;
                 const messagesRaw = data.message;
                 const messages = this.connectors[connector].transform(messagesRaw) || [];
+                console.log("Message:");^M
+                console.log(messagesRaw);^M
+                console.log("Message details:");^M
+                console.log(messages);^M
 
                 for (let monitor of this.monitors) {
```

And I've captured this: https://gist.github.com/mirceaulinic/57e8070f19c0b55be2a1b4ea9ef963d8 (excerpt). This gives some good insights, and might have a clue now on what could be the cause of the frequent updates. I do have a question however, if you search for the timestamp `1579609659.8`, there seems to be several copies of the same message (i.e., same peer AS, host, etc.) - is this expected, or you meant to put the logs elsewhere? Thanks!

**Comment by massimocandela** [comment] 2020-01-21 14:03
Hi @mirceaulinic,

This is interesting! I need to replicate it.
Could you please provide me with the rule in prefixes.yml covering this ip: 195.66.227.90

**Comment by job** [comment] 2020-01-21 14:07
I just want to say you guys rock :-)

**Comment by mirceaulinic** [comment] 2020-01-21 14:26
Hrm, `195.66.227.90` isn't one of the prefixes I'm monitoring... in the gist above, this address appears under `peer: '195.66.227.90',` which I assume is used in the peering RIS <> AS51185 for the full table research feed (BTW, the updates from 51185 seems very frequent - not sure if that's any relevant at this point).

**Comment by massimocandela** [comment] 2020-01-21 14:43
Sorry, I provided you with the peer instead of the prefix. I meant `206.189.244.0/22`.
Anyway, I think I already have all the information I need. I will let you know asap.

**Comment by mirceaulinic** [comment] 2020-01-21 14:47
Okay, great. Just in case, here's what I have for that prefix :-)

```yaml
"206.189.244.0/22":                        
  description: "LON1 909"
  asn: 14061                               
  ignoreMorespecifics: false               
  ignore: false  
```

**Comment by massimocandela** [comment] 2020-01-21 20:13
Well done @mirceaulinic, you discovered what I believe is a bug in RIPE RIS streaming.
Good news: **It does not affect the correct monitoring**

I managed to confirm my supposition, I'll try to explain it below. 
In your configuration you have the following two rules:
```yaml
206.189.244.0/22:                        
  description: LON1 909
  asn: 14061                               
  ignoreMorespecifics: false               
  ignore: false  

options:
  monitorASns:
    14061:
      group: default
```


These rules partially overlap when `206.189.244.0/22` is announced by its correct origin `14061`. 

In RIS, multiple subscriptions are served in the same channel. The overlap in the subscriptions provokes duplication of the messages in the channel (once for the first rule, once for the second, same md5 hashing of the content).

As I said, it doesn't affect the monitoring. Also, only if the `monitorASns` is set the issue is triggered. Anyway, this is provoking transmission and parsing of useless messages.

I reported this to the RIPE RIS team. I'm writing a local patch because I'm not sure when this will be solved in RIPE RIS. See #140

**Comment by mirceaulinic** [comment] 2020-01-22 08:50
> Well done @mirceaulinic, you discovered what I believe is a bug in RIPE RIS streaming.

The story of my life, LOL.

> Good news: It does not affect the correct monitoring

Yes, I confirm it's not affecting the monitoring at all: I was just looking into this to understand better the cause of the frequent re-announcements, and wanted to check in with you if I derp'ed it or there are duplicates indeed :sweat_smile: 

Again, thanks a lot! :pray:

**Comment by massimocandela** [comment] 2020-01-22 11:10
To be clear, the frequent re-announcements are real independently from the duplication.
So there there are 2 phenomena:
* re-announcements or anyway frequent updates
* duplication of them (RIS bug)

The RIS team is working on the second one!
