### ISSUE TITLE
Feature: list of more specific prefixes to ignore

### ISSUE THREAD

**Issue by queldor** [nttgin/BGPalerter#6] opened 2019-08-15 14:46 UTC
Would love a way to add a list of prefixes to ignore when using more specific prefixes

**Comment by smfeldman** [comment] 2019-08-15 18:03
I think I'm asking for the same thing...

Assuming we announce an aggregate 2001:DB8::/32 and some more specific subnets 2001:DB8::/48 and 2001:DB8:0:1::/48.  I'd like to be able to tell bgpalerter to ignore these more specifics but still alert if an unregistered one (e.g. 2001:DB8:0:2::/48) appears.

I have tried (using our real addresses) adding the subnets to prefixes.yml, but still get alerts for them.

**Comment by massimocandela** [comment] 2019-08-17 23:50
Hi, I need some help to understand exactly the feature you are requesting.

For how it works now, the case described by @smfeldman can be achieved with 3 monitored prefixes in prefixes.yml

2001:DB8::/32:
   ...
   ignoreMorespecifics: false

2001:DB8::/48:
   ...
   ignoreMorespecifics: true

2001:DB8:0:1::/48.
   ...
   ignoreMorespecifics: true


The most specific rule will match, so:
- when 2001:DB8::/48 appears, the matched rule is 2001:DB8::/48 and if the origin AS is respected, nothing will happen (because this rule means "this prefix is supposed to be announced and by this AS")
- when 2001:DB8:0:2::/48 appears, the matched rule is 2001:DB8::/32 and an alert will be triggered (because this means "there is no rule for this specific prefix, which it's not supposed to be announced and it cannot be ignored because the matched less specific says ignoreMorespecifics: false").

Maybe I didn't get what you mean with ignore. Let me know.

**Comment by queldor** [comment] 2019-08-17 23:56
Right now, the below is happening 

2001:DB8::/48:
  asn: 2
  ignoreMorespecifics: true


2001:DB8::/32:
  asn: 1
  ignoreMorespecifics: false

if 2001:DB8::/48 comes in w/ ASN 2 and if generates an alerts under 2001:DB8::/32 asn 1

so we would want to ignore 2001:DB8::/48 for asn 1

**Comment by massimocandela** [comment] 2019-08-18 21:43
That was not an intended behavior. It should be fixed now.

**Comment by smfeldman** [comment] 2019-08-19 05:17
I have been running the new version for a few hours now, and it seems to be working correctly.  I only see alerts for more specifics that I haven't specified in prefixes.yml, and the ones I did specify are properly ignored.

**Comment by massimocandela** [comment] 2019-08-19 09:10
Good! I'm going to close this, feel free to re-open it if something is not like it should.

**Closed by massimocandela** 2019-08-19 09:10 UTC
