### ISSUE TITLE
The monitorASns option in prefixes.yml triggers double messages from RIPE RIS

### ISSUE THREAD

**Issue by massimocandela** [nttgin/BGPalerter#140] opened 2020-01-21 20:11 UTC
**Describe the bug**
The `monitorASns` option in prefixes.yml triggers double messages.
The issue doesn't affect the normal monitoring but increases the number of messages that have to be parsed.

This is an issue of RIPE RIS. In the meanwhile that this is fixed on their side, we could deploy a filter in BGPalerter to drop duplicates.

Derived from: https://github.com/nttgin/BGPalerter/issues/114

**Provide an example**
```yaml
206.189.244.0/22:                        
  description: LON1 909
  asn: 14061                               
  ignoreMorespecifics: false               
  ignore: false  

options:
  monitorASns:
    14061:
      group: default
```
These rules partially overlap when `206.189.244.0/22` is announced by its correct origin `14061`. 

In RIS, multiple subscriptions are served in the same channel. The overlap in the subscriptions provokes duplication of the messages in the channel (once for the first rule, once for the second, same md5 hash of the content).

Example of duplicates:
```
IDENTICAL: d69be6a54012637ad749f07e59957ee3 {
  type: 'announcement',
  prefix: '165.227.224.0/20',
  peer: '187.16.217.59',
  path: Path { value: [ [AS], [AS], [AS] ] },
  originAS: AS { numbers: [ 14061 ], ASset: false, _valid: true },
  nextHop: '187.16.217.59',
  aggregator: null,
  timestamp: 1579634518760,
  communities: [ [ 23106, 4009 ] ]
}
IDENTICAL: 8a810904e54455e2d06badb007c48a3d {
  type: 'announcement',
  prefix: '174.138.104.0/22',
  peer: '187.16.217.59',
  path: Path { value: [ [AS], [AS], [AS] ] },
  originAS: AS { numbers: [ 14061 ], ASset: false, _valid: true },
  nextHop: '187.16.217.59',
  aggregator: null,
  timestamp: 1579634518760,
  communities: [ [ 23106, 4009 ] ]
}
IDENTICAL: 5e8a57456fe1f5ea7215f772f6d35bc0 {
  type: 'announcement',
  prefix: '167.172.48.0/20',
  peer: '187.16.217.59',
  path: Path { value: [ [AS], [AS], [AS] ] },
  originAS: AS { numbers: [ 14061 ], ASset: false, _valid: true },
  nextHop: '187.16.217.59',
  aggregator: null,
  timestamp: 1579634518760,
  communities: [ [ 23106, 4009 ] ]
}
IDENTICAL: 255d417c4219261e0b99b69f3bbca759 {
  type: 'announcement',
  prefix: '188.166.132.0/22',
  peer: '187.16.217.59',
  path: Path { value: [ [AS], [AS], [AS] ] },
  originAS: AS { numbers: [ 14061 ], ASset: false, _valid: true },
  nextHop: '187.16.217.59',
  aggregator: null,
  timestamp: 1579634518760,
  communities: [ [ 23106, 4009 ] ]
```

**Expected behavior**
RIPE RIS should send only one message if multiple rules are satisfied, not duplicated messages, one for each rule.

I reported this to the RIPE RIS team. In the meanwhile, an expected behaviour for a patch is to hash the BGP messages and filter out duplicates.

**Are you using the binary or the source code?**
Not relevant

**Comment by chrisamin** [comment] 2020-01-22 09:47
Hi Massimo. This looks like a bug in RIS Live because there should never be duplicate messages, regardless of how many filters or subscriptions are combined in a session.

Is this caused by combining filters (prefix + ASN in the same ris_subscribe), or multiple overlapping ris_subscribes?

**Comment by massimocandela** [comment] 2020-01-22 11:33
Hi Chris,

Thanks for your support. I managed to reproduce it by using multiple overlapping ris_subscribe
In particular, one including only the AS and one including only the prefix.

I don't know if prefix + ASN in the same ris_subscribe would create the same tho (but I don't believe so, usually in the same subscription the conditions appear in AND).

**Comment by chrisamin** [comment] 2020-01-22 12:40
I've deployed a fix for this issue, can you see if you can still replicate it?

**Comment by massimocandela** [comment] 2020-01-22 13:38
It works perfectly. Thanks @chrisamin !!

**Closed** 2020-01-22 13:41 UTC
Labels: bug
